# These are supported funding model platforms

liberapay: heliocg

custom:
  - 'https://paypal.me/heliocg'
  - 'https://www.blockchain.com/btc/address/bc1q89ntljt5lk7g9z68f5cjs83qfm2xme7g4hkur7'
  - 'https://etherscan.io/address/0xeef9220639F14E7A0FD825AAAd0574e5a8aD7A4B'
  - 'https://blockchair.com/litecoin/address/ltc1q508qfkd09vyya6c5zkfx4r248pf3ezj9ngjdr2'